# Generated by Django 5.0.4 on 2024-04-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_caught'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='caught',
            name='caught',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('E', 'Escaped')], default='Yes', max_length=1),
        ),
    ]
