# Generated by Django 5.0.4 on 2024-04-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ability_alter_caught_caught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='description',
        ),
    ]
